name: flutter_ble_ots_example
description: A new Flutter project.
publish_to: 'none' 
repository: https://github.com/appsfactorygmbh/flutter-ble-ots

version: 1.0.0+1
topics:
  - bluetooth 

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  riverpod: ^2.3.6
  hooks_riverpod: ^2.3.6
  flutter_reactive_ble: ^5.1.1
  intl: ^0.18.1
  flutter_riverpod: ^2.3.6
  meta: ^1.9.1
  flutter_hooks: ^0.18.6
  flutter_ble_ots: 
    path: flutter_ble_ots
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.4.2
  build_runner: ^2.4.6

flutter:

  uses-material-design: true
