name: flutter_ble_ots
description: Bluetooth Low Energy Object Transfer Service
version: 0.0.2
homepage: 'https://appsfactory.de'
repository: https://github.com/appsfactorygmbh/flutter-ble-ots


environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  convert: ^3.1.1


